### ISSUE TITLE
Make a dedicated portal for feathers-objection ?

### ISSUE THREAD

**Issue by mdartic** [feathersjs-ecosystem/feathers-objection#103]
Like https://hooks-common.feathersjs.com/ ?

Hi, first, thanks **a lot** for this amazing work.

Objection.js is a really good lib, and make this available so nicely in Feathers is sooo great !

I find your documentation interesting, but, I'm still searching examples for some of the available options.

I'm asking myself if a web portal like hooks, based on VuePress, and maybe respecting the same colors could be a nice thing ?

What do you think about ?
I could give a try if you find this useful.

**Comment by dekelev** [comment]
Hi @mdartic , thanks!

I'm aware that it's hard to figure out the right usage of many query & params operators and it would also make the README page too long if I'll add all the examples for each operator.

Since every operator have tests, you can easily find examples in the test file, but It's just a workaround until we can layout nice examples for all the operators.

I'm not sure that this worth creating and maintaining an external dedicated website when these examples can be added to GitHub wiki pages inside the repo.

Anyway, it will take some time to prepare all these examples and I don't have much free time these days, so I will keep this in mind and will get to it eventually.

**Comment by mdartic** [comment]
Ok,

If you think it could be a good option, don't hesitate to ask, I could propose you a draft, and you could say go/nogo.

Your Readme is really fine and we can make a search & find quickly.

The vuepress documentation (like feathers one, or vuejs tools) is quick to setup, and quite easy to industrialize to publish.

Thanks again for all this amazing work.
