### ISSUE TITLE
"NotFound: No record found for id ‘null’."  when using query for remove and patch which returns no results. 

### ISSUE THREAD

**Issue by mrichtsfeld** [feathersjs-ecosystem/feathers-objection#118]
```
await viewStateService.remove(null, {
     query: { dataSourceId: ds.id },
     transaction,
});
```

This sample query returns no result in some cases which throws an error. Shouldn't it be a valid case to have no results in a query? (same error is thrown for "patch")

[Error is thrown here](https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L811)

There seem to be two possible solutions. Remove the error which creates a breaking change or adding an option (something like "noErrorOnEmtpyQueries") which would not break anything. 

I'm happy to create a pull request once we have discussed the solution.

**Comment by dekelev** [comment]
Please check if the $noSelect query operator can be used to solve your
use-cases.

בתאריך יום ב׳, 21 בספט׳ 2020, 9:32, מאת Martin Richtsfeld ‏<
notifications@github.com>:

**Comment by mrichtsfeld** [comment]
Thank you for your quick reply. 

The $noSelect helps to avoid throwing the error, but on remove it does not return anything even if objects to remove exist (which is the point of the option I guess). However, also to the channel {} is published which does not give any information about what has been removed. Is this the intended behaviour? It might cause further issues when we are using a reactive listener on the client. 

I think the main question is if there should be an error when a query is not returning any object. Shouldn't it just return an empty array. The $noSelect seems more like a quick fix for this problem.

Please let me know what you think. Thanks for your help.

**Comment by avimar** [comment]
It was definitely a surprise to me when delete was throwing an error when the IDs didn't exist. But I was able to `catch` the error.

Not sure if this needs to be "fixed".

**Comment by mrichtsfeld** [comment]
I use this quite often in my hooks for data cleanup and adding a try catch everywhere just adds a lot of unnecessary boilerplate code which makes the whole source code quite messy. I would prefer to find a clean solution for that.

**Comment by mrichtsfeld** [comment]
@dekelev what do you think about this issue? `$noSelect` also has its issues not returning anything. I'm happy to implement either the solution of not throwing an error by default or adding an option for the service as mentioned above.

**Comment by dekelev** [comment]
`$noSelect` returns what it can from its context and its only goal is to skip a SELECT query and just perform the requested action to improve performance.

`patch` method will update a record and then query for it with the given `id` & `query`. That's why `$noSelect` can be used with `patch` as a workaround when `patch` changes the data that the `query` targets and fails with not-found error.

`remove` method will select the record and will only then delete it and return the record from the previous SELECT query.

Both will throw not-found error when a given `query` results with 0 records, even if the `id` is valid.

This behavior is common to all FeathersJS database adapters since FeathersJS v4 and is explained [here](https://docs.feathersjs.com/guides/migrating.html#querying-by-id).

**Comment by mrichtsfeld** [comment]
Got it. I will handle it on my end. Thank you very much for the clarification.
