### ISSUE TITLE
Is it possible to perform left joins?

### ISSUE THREAD

**Issue by rolandvar** [feathersjs-ecosystem/feathers-objection#70]
Good evening, I'm trying to run a simple query using this library.

Good evening, I'm trying to run a simple query using this library

`SELECT * FROM modules m
LEFT JOIN students_modules sm ON (sm.idModule = m.id AND sm.idStudent = 1)`

This is my modules.model.js
```
class modules extends Model {
  static get tableName() {
    return 'modules';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['id', 'description'],
      properties: {
        idPreModule: { type: 'integer' },
        title: { type: 'string' },
        description: { type: 'string' }
      }
    };
  }

  static get relationMappings() {
    const Student = require('./student.model')();

    return {
      students: {
        relation: Model.ManyToManyRelation,
        modelClass: Student,
        join: {
          from: 'modules.id',
          through: {
            from: 'students_modules.idModule',
            to: 'students_modules.idStudent'
          },
          to: 'student.idUtente'
        }
      }
    };
  }
}
```

Thanks for your help

**Comment by dekelev** [comment]
Model looks fine. to query like LEFT JOIN, use something like:

```
modules.find({
  query: {
    $eager: 'students'
  }
}
```

but with your example, seems like you should query on the students service. something like:

```
students.get(1, {
  query: {
    $eager: 'modules'
  }
}
```

**Comment by rolandvar** [comment]
> Model looks fine. to query like LEFT JOIN, use something like:
> 
> ```
> modules.find({
>   query: {
>     $eager: 'students'
>   }
> }
> ```
> 
> but with your example, seems like you should query on the students service. something like:
> 
> ```
> students.get(1, {
>   query: {
>     $eager: 'modules'
>   }
> }
> ```

These two solutions do not return the same result set as my query.
In the first solution you retrive all the modules with ALL the students.
In the second solution you retrive only the modules associated with the students' id 1

I would like to take all the modules from the database and know which of the modules is associated with the students' id 1.

**Comment by dekelev** [comment]
Do you want to pull all modules from the database with the studentId/student even if it doesn't match studentId 1 and then check which modules belongs to studentId 1? Or that you're trying to pull all modules of studentId 1.

The second query pulls all modules that belongs to studentId 1, which seems to fit your use case, but you'll need to use the students & students_modules models instead of the modules & students_modules models.

If you want to avoid querying the students table, then just add simple oneToMany relation from the modules model to the students_modules table without using the `through` property or use only the students_modules model (see examples below).

In case that you're adding query on a relation and want to filter out rows that doesn't match the query, use [$joinRelation or $joinEager](https://github.com/feathersjs-ecosystem/feathers-objection#query-operators) if it works better for you. for example:

```
modules.find({
  query: {
    'students_modules.studentId': 1,
    $eager: 'students_modules',
    $joinRelation: 'students_modules'
  }
}

or

students_modules.find({
  query: {
    studentId: 1,
    $eager: 'modules'
  }
}
```
