### ISSUE TITLE
$sort a parent by a child field with $eager $joinRelation

### ISSUE THREAD

**Issue by bradrisse** [feathersjs-ecosystem/feathers-objection#78]
I have a parent table `product` and two relations: hasOne `brand`, hasMany `attributes`. I'm trying to filter products by brand name like this `{{apiUrl}}/product?$eager=[brand, attributes]&$joinRelation=[brand]&$sort[brand.name]=1`, but I'm receiving an error

`"select distinct \"product\".* from \"product\" inner join \"brand\" on \"brand\".\"id\" = \"product\".\"brandId\" where \"product\".\"name\" = $1 order by \"brand\".\"name\" asc limit $2 - for SELECT DISTINCT, ORDER BY expressions must appear in select list"`

due to this line https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/src/index.js#L290 using `distinct`

I tried also using `$joinEager`, but I need pagination and the limits get applied to the relations. $limit: 10, 1 product, 1 brand, 10 attributes, only a single product ends up in the result. 

By removing the `distinct` portion I get the results as intended.

1. What are the unintended consequences of removing `distinct` ?
2. Is there another way to sort a parent by a child field while still maintaining pagination with hasOne and hasMany relations?

**Comment by dekelev** [comment]
MySQL & Postgres do not allow order by field of a joined table, unless it's a selected field.

`distinct` enables parent pagination for JOIN queries by grouping all parent rows to a single one at the DB level.

You can add `$select: ['product.*', 'brand.name as brand.name']` to your query as a workaround, but with one-to-many relation, parent pagination will still be unreliable, with or without `distinct`, because multiple rows can return for each parent.
